export const state = {
  className: "user",
  avatar: "../img/user_profile.svg",
  login: "",
  first_name: "",
  second_name: "",
  display_name: "",
  email: "",
  phone: "",
  titleClass: "user__title",
  buttons: {
    submit: {
      tag: "a",
      link: "#",
      className: "btn",
      title: "Редактировать",
      dataPage: "settings",
    },
    changePswLink: {
      tag: "a",
      link: "#",
      className: "btn btn-red",
      title: "Изменить пароль",
      dataPage: "change_password",
    },
    back: {
      tag: "a",
      link: "#",
      className: "back-link",
      title: "Вернуться",
      dataPage: "chats",
      hr: true,
    },
    logout: {
      tag: "a",
      link: "#",
      className: "logout-link",
      title: "Выйти",
    },
  },
};
