export const state = {
  className: "edit-user",
  titleClass: "edit-user__title",
  title: "Александр",
  img: "./img/user_profile.svg",
  form: {
    action: "user/edit",
    method: "post",
    className: "edit-user__form form",
    inputs: {
      email: {
        type: "email",
        name: "email",
        className: "form__input email",
        value: "pochta@yandex.ru",
        label: "Почта",
      },
      login: {
        type: "text",
        name: "login",
        className: "form__input login",
        value: "Alex",
        label: "Логин",
      },
      firstName: {
        type: "text",
        name: "first_name",
        className: "form__input first_name",
        value: "Александр",
        label: "Имя",
      },
      secondName: {
        type: "text",
        name: "second_name",
        className: "form__input second_name",
        value: "Александров",
        label: "Фамилия",
      },
      chatsName: {
        type: "text",
        name: "chats_name",
        className: "form__input chats_name",
        value: "Алекс",
        label: "Имя в чате",
      },
      phone: {
        type: "tel",
        name: "phone",
        className: "form__input phone",
        value: "+7 (909) 967 30 30",
        label: "Телефон",
      },
      file: {
        type: "file",
        name: "file",
        className: "form__input file",
      },
    },
    buttons: {
      submit: {
        tag: "button",
        type: "submit",
        className: "btn",
        title: "Редактировать",
      },
      userLink: {
        tag: "a",
        link: "#",
        className: "form__user-link form__link",
        title: "Выйти",
        dataPage: "user",
      },
    },
  },
};
